### PR TITLE
added thank class

### PR DESCRIPTION
**Pull request by Gyeshwanth**
hi Gosi,

please review code i added thank 

regards
yeshwanth

### CODE REVIEW

**Comment by GosiYeshwnath** [comment]
HI yesh,

i checked your code and added unit test

**Comment by Gyeshwanth** [comment]
hi gosi,

unit done.. review code

**Comment by GosiYeshwnath** [comment]
hi yeshu,

ok. merge code
regards
gosi

**Comment by Gyeshwanth** [comment]
hi gosi 

ok done.

**Pull request merged**
